### PR TITLE
Fix multiple results in Repo.One with multiple create type internal transactions

### LINKED ISSUE #367: Multiple contract creates from a single contract error
I created a contract that creates multiple other contracts. It looks like the call to the `internal_transactions` table is looking for 1 creates but received 5 instead. 

```Jul 05 21:52:10 ip-10-0-0-140.poa.internal explorer[20322]: Request: GET /en/transactions/0x2a2829a8094776b41f165c4fa3ed68d6415a0ab62d6b7b4b18b13dd0cbfcf149/internal_transactions
Jul 05 21:52:10 ip-10-0-0-140.poa.internal explorer[20322]: ** (exit) an exception was raised:
Jul 05 21:52:10 ip-10-0-0-140.poa.internal explorer[20322]: ** (Ecto.MultipleResultsError) expected at most one result but got 5 in query:
Jul 05 21:52:10 ip-10-0-0-140.poa.internal explorer[20322]: from t in Explorer.Chain.Transaction,
Jul 05 21:52:10 ip-10-0-0-140.poa.internal explorer[20322]: left_join: i in assoc(t, :internal_transactions),
Jul 05 21:52:10 ip-10-0-0-140.poa.internal explorer[20322]: where: t.hash == ^%Explorer.Chain.Hash{byte_count: 32, bytes: <<42, 40, 41, 168, 9, 71, 118, 180, 31, 22, 92, 79, 163, 237, 104, 214, 65, 90, 10, 182, 45, 107, 123, 75, 24, 177, 61, 208, 203, 252, 241, 73>>},
Jul 05 21:52:10 ip-10-0-0-140.poa.internal explorer[20322]: order_by: [desc: t.block_number, desc: t.index],
Jul 05 21:52:10 ip-10-0-0-140.poa.internal explorer[20322]: select: merge(t, %{created_contract_address_hash: i.created_contract_address_hash}),
Jul 05 21:52:10 ip-10-0-0-140.poa.internal explorer[20322]: preload: [:block, :from_address, :to_address]
Jul 05 21:52:10 ip-10-0-0-140.poa.internal explorer[20322]: (ecto) lib/ecto/repo/queryable.ex:73: Ecto.Repo.Queryable.one/4
Jul 05 21:52:10 ip-10-0-0-140.poa.internal explorer[20322]: (explorer) lib/explorer/chain.ex:706: Explorer.Chain.hash_to_transaction/2
Jul 05 21:52:10 ip-10-0-0-140.poa.internal explorer[20322]: (explorer_web) lib/explorer_web/controllers/transaction_internal_transaction_controller.ex:12: ExplorerWeb.TransactionInternalTransactionController.index/2
Jul 05 21:52:10 ip-10-0-0-140.poa.internal explorer[20322]: (explorer_web) lib/explorer_web/controllers/transaction_internal_transaction_controller.ex:1: ExplorerWeb.TransactionInternalTransactionController.action/2
Jul 05 21:52:10 ip-10-0-0-140.poa.internal explorer[20322]: (explorer_web) lib/explorer_web/controllers/transaction_internal_transaction_controller.ex:1: ExplorerWeb.TransactionInternalTransactionController.phoenix_controller_pipeline/2
```

### Steps to reproduce

View this transaction hash `0x2a2829a8094776b41f165c4fa3ed68d6415a0ab62d6b7b4b18b13dd0cbfcf149` in explorer to replicate the error. 

### Expected behaviour

https://sokol.poaexplorer.com/txid/search/0x2a2829a8094776b41f165c4fa3ed68d6415a0ab62d6b7b4b18b13dd0cbfcf149

### Actual behaviour

Internal server error.

### LINKED ISSUE #383: Transactions with non-matching from and to addresses are shown in the address page
When a parent transaction executes a contract that creates other
contracts, those contract address pages should not include the parent
transaction in the transactions tab (it has non-matching from and to addresses).

### PR DESCRIPTION
**Pull request by tmecklem**
Fixes #367
Fixes #383

### Bug Fixes
* Fixes the transaction details page when a transaction has multiple internal transactions of type create
* Fixes contract address page showing parent transaction with non-matching to and from addresses

### CODE REVIEW

**Comment by acravenho** [comment]
screen shot 2018-07-09 at 6 59 34 pm

@tmecklem Small change: the `call` to the contract comes before the `creates`. Let's order them as they are completed by the VM.

File: apps/explorer/lib/explorer/chain.ex [hunk 1]
```diff
@@ -147,7 +146,7 @@ defmodule Explorer.Chain do
             SELECT t0."hash" address
             FROM "transactions" AS t0
             LEFT OUTER JOIN "internal_transactions" AS i1 ON (i1."transaction_hash" = t0."hash") AND (i1."type" = 'create')
-            WHERE (i1."created_contract_address_hash" = $1)
+            WHERE (i1."created_contract_address_hash" = $1 AND t0."to_address_hash" IS NULL)
```
Comment (amandasposito) [inline apps/explorer/lib/explorer/chain.ex]: Do you think is worth to update the docs to explain this change here?

Comment (tmecklem) [reply apps/explorer/lib/explorer/chain.ex]: I took a couple of unsuccessful attempts at documenting this succinctly and I'd like to think about it a little more. Due to the count query performance needs, there are two disparate places where the same logic applies to identify a "Contract Creation Transaction". I think we should document this well, but I'm not sure exactly how to approach it.

I'd like to merge this and continue to think about this while we build understanding of the other cases of addresses -- specifically tokens and miners/validators.
