### PR TITLE
Prevent holes and fill in holes during realtime indexing

### LINKED ISSUE #421: Real-time indexer skipping blocks
The real-time indexer is currently skipping 1-3 blocks at a time.

### Steps to reproduce

1. Index the entire chain
2. View the blocks page or homepage.

### Expected behaviour

The real-time indexer should be checking every `block_time/2`

### LINKED ISSUE #453: ExplorerWeb.EventHandler crashes when broadcasting a pending transaction
### Steps to reproduce

1. `DEBUG_INDEXER=1 iex -S mix`
2. Wait a few seconds

### Expected behaviour

`ExplorerWeb.Notifier` properly handles pending transactions.

### Actual behaviour

```
iex(1)> [error] GenServer ExplorerWeb.EventHandler terminating
** (MatchError) no match of right hand side value: {:error, :not_found}
    (explorer_web) lib/explorer_web/notifier.ex:34: ExplorerWeb.Notifier.broadcast_transaction/1
    (elixir) lib/enum.ex:737: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:737: Enum.each/2
    (explorer_web) lib/explorer_web/event_handler.ex:26: ExplorerWeb.EventHandler.handle_info/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:chain_event, :transactions, [%Explorer.Chain.Hash{byte_count: 32, bytes: <<2, 110, 52, 134, 176, 226, 72, 208, 228, 148, 103, 240, 32, 34, 118, 23, 83, 22, 230, 107, 83, 211, 97, 112, 231, 21, 192, 56, 183, 192, 122, 62>>}, %Explorer.Chain.Hash{byte_count: 32, bytes: <<7, 6, 93, 196, 173, 233, 61, 207, 243, 205, 118, 167, 0, 81, 243, 99, 2, 1, 161, 206, 115, 23, 206, 163, 161, 104, 115, 147, 65, 131, 142, 118>>}, %Explorer.Chain.Hash{byte_count: 32, bytes: <<16, 154, 196, 88, 36, 11, 207, 222, 173, 52, 129, 158, 138, 216, 146, 254, 77, 127, 227, 180, 109, 70, 242, 28, 204, 130, 175, 55, 150, 164, 16, 81>>}, %Explorer.Chain.Hash{byte_count: 32, bytes: <<22, 64, 91, 28, 203, 242, 51, 34, 65, 189, 229, 116, 194, 15, 120, 168, 63, 71, 74, 40, 82, 12, 109, 31, 131, 165, 100, 187, 131, 43, 89, 5>>}
State: []
```

### PR DESCRIPTION
**Pull request by KronicDeth**
## Blockers
- [x] Test full-index on AWS to check if blocks are still missed during catch-up. (In-progress on @KronicDeth's setup)

Fixes #421 
Fixes #453

### Enhancements
* Remove need for `Indexer.start_monitor` by using `Task.Supervisor.async_nolink` because `Task.Supervisor.async_nolink` monitors the `Task` pid instead of linking, so it does the same thing as our `Indexer.start_monitor`.
* When a catchup_index task completes without error, increase the interval until the next check by 2 if no blocks were missing and decrease it by 2 if blocks were missing.  Minimum interval is the same as the realtime interval while the maximum interval is arbitarily chosen to be 10x the
realtime interval.

### Bug Fixes
* `block_rate` is measured in milliseconds / block, but a rate would blocks / unit-of-time, so rename `block_rate` to `block_interval` to reflect it is the interval between blocks.
* The `realtime_interval` should be half of the `block_interval` to ensure that we don't get stuck in a state where we just miss a new block because using precisely the block rate doesn't account for processing time.  The exact value of half the `block_interval` was chosen for the [Nyquist rules](https://en.wikipedia.org/wiki/Nyquist_frequency)
* Fix typo where `genesis` was `gensis`.
* Instead of scheduling the next realtime index in block_interval / 2 only after the previous one complete, run the realtime index every block_interval / 2 using `:timer.send_interval`.  This ensures that the time it takes to complete the realtime index doesn't slowly build up, which is currently leading a missed block approximately every 15 blocks.
* Remove unused `start_block_number` in `BlockFetcher` state.
* Fix phrasing in log message when genesis task completes.
* Handle output from `Task`s: previously, `BlockFetcher` only had handle_info for the `:DOWN` message from realtime tasks, but when the reason is `:normal`, the `Task` would have succeeded and therefore, the BlockFetcher would also have received a `{ref, :ok}` that was not being matched.
* Allow pending transactions to be broadcast.
* Increase `pool_timeout` from default of 5,000 milliseconds to 10,000 milliseconds to prevent flaky timeouts from `apps/indexer/test/indexer/block_fetcher_test.exs:50` like
    
    ```
    [error] Realtime index stream exited with reason ({:timeout, {GenServer, :call, [#PID<0.596.0>, {:checkout, #Reference<0.851308976.2388656130.16563>, true, 120000}, 5000]}})
    ```

### Incompatible Changes
* `block_rate` option has been renamed to `block_interval`.

## Upgrading

Any `config :index, block_rate: ...` needs to be changed to `config :indexer, block_interval: ...`.  The configs in Git already have these changes.  Only customizations or forks need to be manually updated.

### CODE REVIEW

File: apps/indexer/lib/indexer/bound_interval.ex [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+
+    %__MODULE__{bound_interval | current: new_current}
+  end
+
+  def increase(%__MODULE__{current: current, maximum: maximum} = bound_interval)
+      when is_integer(current) and is_integer(maximum) do
+    new_current =
+      current
+      |> Kernel.*(2)
+      |> min(maximum)
```
Comment (Lucasnar) [inline apps/indexer/lib/indexer/bound_interval.ex]: I think using the Kernel module explicitly here makes the code a little bit harder to understand, unnecessarily. I'd go with a more standard option to keep things simple:

```elixir 
new_current = min(current * 2, maximum)
```

WDYT?

File: apps/indexer/lib/indexer/block_fetcher.ex [hunk 2]
```diff
@@ -45,7 +45,8 @@ defmodule Indexer.BlockFetcher do
       Defaults to #{@blocks_concurrency}.  So upto `blocks_concurrency * block_batch_size` (defaults to
       `#{@blocks_concurrency * @blocks_batch_size}`) blocks can be requested from the JSONRPC at once over all
       connections.
-    * `:block_rate` - The millisecond rate new blocks are published at. Defaults to `#{@block_rate}` milliseconds.
+    * `:block_interval` - The number of millisecond between new blocks being published. Defaults to `#{@block_interval}`
```
Comment (Lucasnar) [inline apps/indexer/lib/indexer/block_fetcher.ex]: `millisecond` -> `milliseconds`?

File: apps/indexer/lib/indexer/bound_interval.ex (hunk 1 above)
Comment (KronicDeth) [reply apps/indexer/lib/indexer/bound_interval.ex]: Sure

File: apps/indexer/lib/indexer/block_fetcher.ex [hunk 3]
```diff
@@ -59,64 +60,139 @@ defmodule Indexer.BlockFetcher do
...
+    end
+
+    Process.demonitor(ref, [:flush])
+
+    {:noreply, %__MODULE__{state | realtime_task_by_ref: running_realtime_task_by_ref}}
   end
 
-  def handle_info({:DOWN, _ref, :process, pid, _reason}, %{genesis_task: pid} = state) do
-    Logger.error(fn -> "gensis index stream exited. Restarting" end)
+  def handle_info({:DOWN, ref, :process, pid, reason}, %__MODULE__{realtime_task_by_ref: realtime_task_by_ref} = state) do
```
Comment (Stamates) [inline apps/indexer/lib/indexer/block_fetcher.ex]: Can we move this function up so it's right below the other `def handle_info({:DOWN, ref, :process, pid, reason}, %__MODULE__{catchup_task: %Task{pid: pid, ref: ref}} = state) do` with a matching signature?

File: apps/indexer/lib/indexer/block_fetcher.ex [hunk 4]
```diff
@@ -155,17 +234,42 @@ defmodule Indexer.BlockFetcher do
...
-    count = Enum.count(missing_ranges)
 
-    debug(fn -> "#{count} missed block ranges between #{latest_block_number} and genesis" end)
+    case latest_block_number do
+      # let realtime indexer get the genesis block
+      0 ->
+        0
+
+      _ ->
+        # realtime indeer gets the current latest block
```
[the remark this answers is not in the document]
Comment (KronicDeth) [reply apps/indexer/lib/indexer/block_fetcher.ex]: [The guy](https://github.com/KronicDeth) that writes the [IntelliJ Elixir plugin](https://github.com/KronicDeth/intellij-elixir) should figure out how to [enable spell checking](https://github.com/KronicDeth/intellij-elixir/issues/1169) inside of comments.

**Comment by KronicDeth** [comment]
@Lucasnar fixed your comments.  Can I get an Approve for the merge check?

@acravenho my AWS run did not have gaps.  Are you seeing the same with the newest version and can Approve?

File: apps/indexer/lib/indexer/block_fetcher.ex (hunk 4 above)
[the remark this answers is not in the document]
Comment (Lucasnar) [reply apps/indexer/lib/indexer/block_fetcher.ex]: LOL

File: apps/indexer/lib/indexer/block_fetcher.ex (hunk 3 above)
Comment (KronicDeth) [reply apps/indexer/lib/indexer/block_fetcher.ex]: I had the clauses together based on the matching lifetime stage of the task like you're asking for, but I switched to this format where all stages for the same task are together now.

File: apps/explorer_web/lib/explorer_web/notifier.ex [hunk 5]
```diff
@@ -35,7 +35,8 @@ defmodule ExplorerWeb.Notifier do
       Chain.hash_to_transaction(
```
[the remark this answers is not in the document]
Comment (Stamates) [reply apps/explorer_web/lib/explorer_web/notifier.ex]: It doesn't really matter though since I believe we're going to be reworking this in our next PR to subscribe to real-time indexer events only (and bulk fetch transactions with a query before broadcasting).

File: apps/indexer/lib/indexer/block_fetcher.ex (hunk 3 above)
Comment (KronicDeth) [reply apps/indexer/lib/indexer/block_fetcher.ex]: Looking at the decompiled bytecode, having the `:DOWN` check near each other doesn't matter for the generated code, the first thing that is done in my version of the code is to check the arity of the tuple:

```
func_info(module: Indexer.BlockFetcher, function: :handle_info, arity: 2)
  label(48)
      is_tuple(fail_label: 67, argument: x(0))
      select_tuple_arity(tuple: x(0), fail_label: 47, arity_to_label: list(2, label(49), 5, label(63)))

```

Add if the `catchup_task` `:DOWN` clause fails, if jumps to the the `realtime_task` `:DOWN` clause

```
  label(49)
      get_tuple_element(source: x(0), element_number: 0, destination: x(2))
      get_tuple_element(source: x(0), element_number: 1, destination: x(3))
      is_map(fail_label: 61, argument: x(1))
      get_map_elements(fail_label: 61, source: x(1), key_to_destination: list(:__struct__, x(7), :catchup_block_number, x(6), :catchup_bound_interval, x(5), :catchup_task, x(4)))
      is_eq_exact(fail_label: 61, left: x(7), right: Indexer.BlockFetcher)
      is_map(fail_label: 61, argument: x(4))
      get_map_elements(fail_label: 61, source: x(4), key_to_destination: list(:__struct__, x(9), :ref, x(8)))
      is_eq_exact(fail_label: 61, left: x(9), right: Task)
      is_eq_exact(fail_label: 61, left: x(8), right: x(2))
      is_integer(fail_label: 61, argument: x(3))

....

label(61)
      is_eq_exact(fail_label: 47, left: x(3), right: :ok)
      is_map(fail_label: 47, argument: x(1))
      get_map_elements(fail_label: 47, source: x(1), key_to_destination: list(:__struct__, x(5), :realtime_task_by_ref, x(4)))
      is_eq_exact(fail_label: 47, left: x(5), right: Indexer.BlockFetcher)
```

Disassembly from [IntelliJ Elixir](https://github.com/KronicDeth/intellij-elixir) [Code](https://github.com/KronicDeth/intellij-elixir) tab of the BEAM Chunks viewer.

File: apps/explorer_web/lib/explorer_web/notifier.ex (hunk 5 above)
[the remark this answers is not in the document]
Comment (KronicDeth) [reply apps/explorer_web/lib/explorer_web/notifier.ex]: I added your change before this comment.

File: apps/indexer/lib/indexer/block_fetcher.ex (hunk 4 above)
[the remark this answers is not in the document]
Comment (eagle-te) [reply apps/indexer/lib/indexer/block_fetcher.ex]: hahahahaha

;)
