### PR TITLE
Rechunk batch JSONRPC request when 413 is returned

### LINKED ISSUE #254: Detect 413 Request Entity Too Large and autoscale down batches
While running `iex -S mix` locally for development, the `eth_getBlockByNumber` batch call blow up with a `failed to decode json payload` error that contained an HTML error with title `413 Request Entity Too Large` from the nginx server that is the reverse proxy for https://sokol.poa.network.  We should check for 413 and autoscale down batches when it occurs.

<details>

```
[error] failed to decode json payload:

    url: "https://sokol.poa.network"

    body: "<html>\r\n<head><title>413 Request Entity Too Large</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>413 Request Entity Too Large</h1></center>\r\n<hr><center>nginx/1.10.3 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n"

    posted payload: [%{"id" => 2848556, "jsonrpc" => "2.0", "method" => "eth_getBlockByNumber", "params" => ["0x2B772C", true]}, %{"id" => 2848555, "jsonrpc" => "2.0", "method" => "eth_getBlockByNumber", "params" => ["0x2B772B", true]}, %{"id" => 2848554, "jsonrpc" => "2.0", "method" => "eth_getBlockByNumber", "params" => ["0x2B772A", true]}, %{"id" => 2848553, "jsonrpc" => "2.0", "method" => "eth_getBlockByNumber", "params" => ["0x2B7729", true]}, %{"id" => 2848552, "jsonrpc" => "2.0", "method" => "eth_getBlockByNumber", "params" => ["0x2B7728", true]}, %{"id" => 2848551, "jsonrpc" => "2.0", "method" => "eth_getBlockByNumber", "params" => ["0x2B7727", true]}, %{"id" => 2848550, "jsonrpc" => "2.0", "method" => "eth_getBlockByNumber", "params" => ["0x2B7726", true]}, %{"id" => 2848549, "jsonrpc" => "2.0", "method" => "eth_getBlockByNumber", "params" => ["0x2B7725", true]}, %{"id" => 2848548, "jsonrpc" => "2.0", "method" => "eth_getBlockByNumber", "params" => ["0x2B7724", true]}, %{"id" => 2848547, "jsonrpc" => "2.0", "method" => "eth_getBlockByNumber", "params" => ["0x2B7723", true]}, %{"id" => 2848546, "jsonrpc" => "2.0", "method" => "eth_getBlockByNumber", "params" => ["0x2B7722", true]}, %{"id" => 2848545, "jsonrpc" => "2.0", "method" => "eth_getBlockByNumber", "params" => ["0x2B7721", true]}, %{"id" => 2848544, "jsonrpc" => "2.0", "method" => "eth_getBlockByNumber", "params" => ["0x2B7720", true]}, %{"id" => 2848543, "jsonrpc" => "2.0", "method" => "eth_getBlockByNumber", "params" => ["0x2B771F", true]}, %{"id" => 2848542, "jsonrpc" => "2.0", "method" => "eth_getBlockByNumber", "params" => ["0x2B771E", true]}, %{"id" => 2848541, "jsonrpc" => "2.0", "method" => "eth_getBlockByNumber", "params" => ["0x2B771D", true]}, %{"id" => 2848540, "jsonrpc" => "2.0", "method" => "eth_getBlockByNumber", "params" => ["0x2B771C", true]}, %{"id" => 2848539, "jsonrpc" => "2.0", "method" => "eth_getBlockByNumber", "params" => ["0x2B771B", true]}, %{"id" => 2848538, "jsonrpc" => "2.0", "method" => "eth_getBlockByNumber", "params" => ["0x2B771A", true]}, %{"id" => 2848537, "jsonrpc" => "2.0", "method" => "eth_getBlockByNumber", "params" => ["0x2B7719", true]}, %{"id" => 2848536, "jsonrpc" => "2.0", "method" => "eth_getBlockByNumber", "params" => ["0x2B7718", true]}, %{"id" => 2848535, "jsonrpc" => "2.0", "method" => "eth_getBlockByNumber", "params" => ["0x2B7717", true]}, %{"id" => 2848534, "jsonrpc" => "2.0", "method" => "eth_getBlockByNumber", "params" => ["0x2B7716", true]}, %{"id" => 2848533, "jsonrpc" => "2.0", "method" => "eth_getBlockByNumber", "params" => ["0x2B7715", true]}, %{"id" => 2848532, "jsonrpc" => "2.0", "method" => "eth_getBlockByNumber", "params" => ["0x2B7714", true]}, %{"id" => 2848531, "jsonrpc" => "2.0", "method" => "eth_getBlockByNumber", "params" => ["0x2B7713", true]}, %{"id" => 2848530, "jsonrpc" => "2.0", "method" => "eth_getBlockByNumber", "params" => ["0x2B7712", true]}, %{"id" => 2848529, "jsonrpc" => "2.0", "method" => "eth_getBlockByNumber", "params" => ["0x2B7711", true]}, %{"id" => 2848528, "jsonrpc" => "2.0", "method" => "eth_getBlockByNumber", "params" => ["0x2B7710", true]}, %{"id" => 2848527, "jsonrpc" => "2.0", "method" => "eth_getBlockByNumber", "params" => ["0x2B770F", true]}, %{"id" => 2848526, "jsonrpc" => "2.0", "method" => "eth_getBlockByNumber", "params" => ["0x2B770E", true]}, %{"id" => 2848525, "jsonrpc" => "2.0", "method" => "eth_getBlockByNumber", "params" => ["0x2B770D", true]}, %{"id" => 2848524, "jsonrpc" => "2.0", "method" => "eth_getBlockByNumber", "params" => ["0x2B770C", true]}, %{"id" => 2848523, "jsonrpc" => "2.0", "method" => "eth_getBlockByNumber", "params" => ["0x2B770B", true]}, %{"id" => 2848522, "jsonrpc" => "2.0", "method" => "eth_getBlockByNumber", "params" => ["0x2B770A", true]}, %{"id" => 2848521, "jsonrpc" => "2.0", "method" => "eth_getBlockByNumber", "params" => ["0x2B7709", true]}, %{"id" => 2848520, "jsonrpc" => "2.0", "method" => "eth_getBlockByNumber", "params" => ["0x2B7708", true]}, %{"id" => 2848519, "jsonrpc" => "2.0", "method" => "eth_getBlockByNumber", "params" => ["0x2B7707", true]}, %{"id" => 2848518, "jsonrpc" => "2.0", "method" => "eth_getBlockByNumber", "params" => ["0x2B7706", true]}, %{"id" => 2848517, "jsonrpc" => "2.0", "method" => "eth_getBlockByNumber", "params" => ["0x2B7705", true]}, %{"id" => 2848516, "jsonrpc" => "2.0", "method" => "eth_getBlockByNumber", "params" => ["0x2B7704", true]}, %{"id" => 2848515, "jsonrpc" => "2.0", "method" => "eth_getBlockByNumber", "params" => ["0x2B7703", true]}, %{"id" => 2848514, "jsonrpc" => "2.0", "method" => "eth_getBlockByNumber", "params" => ["0x2B7702", true]}, %{"id" => 2848513, "jsonrpc" => "2.0", "method" => "eth_getBlockByNumber", "params" => ["0x2B7701", true]}, %{"id" => 2848512, "jsonrpc" => "2.0", "method" => "eth_getBlockByNumber", "params" => ["0x2B7700", ...]}, %{"id" => 2848511, "jsonrpc" => "2.0", "method" => "eth_getBlockByNumber", "params" => [...]}, %{"id" => 2848510, "jsonrpc" => "2.0", "method" => "eth_getBlockByNumber", ...}, %{"id" => 2848509, "jsonrpc" => "2.0", ...}, %{"id" => 2848508, ...}, %{...}, ...]
```

</details>

### PR DESCRIPTION
**Pull request by KronicDeth**
Fixes #254

### Bug Fixes
* When status 413 Request Entity Too Large is returned from JSONRPC, we can split the batch in half and try again.  Continuing to break up the chunks of the batch until we succeed or hit 1 request in the chunk, in which case we still need to error.
* Use `:capture_log` `@moduletag` to quiet `Statistics.Server` shutdown during tests.

### CODE REVIEW

File: apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex [hunk 1]
```diff
@@ -365,19 +412,20 @@ defmodule EthereumJSONRPC do
 
   defp encode_json(data), do: Jason.encode_to_iodata!(data)
 
-  defp decode_json(body, posted_payload, url) do
-    Jason.decode!(body)
+  defp decode_json(response_body, response_status_code, request_body, request_url) do
+    Jason.decode!(response_body)
   rescue
     Jason.DecodeError ->
       Logger.error("""
```
Comment (alexgaribay) [inline apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex]: We should probably make the message into an anonymous function.
