### PR TITLE
Use nil Balance value to indicate unfetched

### LINKED ISSUE #491: Runaway postgres processes
I frequently have runaway postgres processes after stopping the indexer, and they block other activity (like adding a column, etc). The processes seemingly need to be killed every time. Most recently, I ran the indexer overnight, and there were two stuck processes this morning that continued running for several hours. Both were running this query:

> SELECT a0."hash", b4."number" FROM "addresses" AS a0 LEFT OUTER JOIN "internal_transactions" AS i1 ON a0."hash" IN (i1."created_contract_address_hash",i1."from_address_hash",i1."to_address_hash") LEFT OUTER JOIN "logs" AS l2 ON l2."address_hash" = a0."hash" LEFT OUTER JOIN "transactions" AS t3 ON t3."hash" IN (i1."transaction_hash",l2."transaction_hash") OR a0."hash" IN (t3."from_address_hash",t3."to_address_hash") LEFT OUTER JOIN "blocks" AS b4 ON (b4."hash" = t3."block_hash") OR (b4."miner_hash" = a0."hash") LEFT OUTER JOIN "balances" AS b5 ON (b5."address_hash" = a0."hash") AND (b5."block_number" = b4."number") WHERE ((NOT (b4."number" IS NULL) AND b5."address_hash" IS NULL) AND b5."block_number" IS NULL) GROUP BY a0."hash", b4."number"

### Environment

* Elixir & Erlang/OTP versions (`elixir -v`): 
```
Erlang/OTP 20 [erts-9.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false]
Elixir 1.6.5 (compiled with OTP 19)
```
* Operating System: macOS High Sierra 10.13.6
Postgres: 10.4

### Steps to reproduce

* Start the indexer on an empty database and let it run for a while (overnight is usually enough to reproduce)
* Stop the indexer
* Note there are one or more postgres OS processes consuming as much CPU at they can
* Execute `select * from pg_stat_activity where datname = 'explorer_dev'` and note several pg processes executing the same query noted at the beginning of the issue description.

### Expected behaviour

Stopping the elixir processes should eventually result in the postgres processes winding down

### Actual behaviour

The postgres processes continue to consume CPU resources seemingly indefinitely.

### PR DESCRIPTION
**Pull request by KronicDeth**
Resolves #491 

**Note:** This does not fix the underlying issue with `Ecto.Repo.stream` that killing the node leaves the query running in Postgres.  This just makes the query that hangs take less time, so it is less likely to be running on node death.  Fixing the zombie Postgres query will require changes upstream in `Ecto`.

## Blockers
- [x] Test against Sokol on AWS (assigned to @KronicDeth)

### Bug Fixes
* Balances will be created when a given (address_hash, block_number) is first seen, but with a `nil` value.  The BalanceFetcher will stream this value is `NULL` rows on restart to initialize the queue.
* Remove flaky tests that keep killing the builds.

### Incompatible Changes
* `Balance`s will be created with `nil` `value` when a given `address_hash` and `block_number` pair are encountered to mark that the `value` needs to be fetched.  This means `Balance` `value` cannot be assumed to be non-`nil`.

## Upgrading

This changes requires `Balance` to be create with `value` `nil` to indicate unfetched.  Since this change is being made because the query to find all `{address_hash, block_number}` without a balance takes 10s of minutes, there is no data migration and a reset and reindex is required:

1. `mix do ecto.drop, ecto.create, ecto.migrate`
2. `DEBUG_INDEXER iex -S mix`

For code changes, `Balance`s need to be filtered for unfetched (where `value` is `nil`).

### CODE REVIEW

**Comment by KronicDeth** [comment]
24 seconds to get 1/4 million rows of unfetched balances.

**Comment by KronicDeth** [comment]
Total query runtime: 34 secs. 440269 rows affected.

File: apps/indexer/lib/indexer/block_fetcher.ex [hunk 1]
```diff
@@ -203,11 +208,15 @@ defmodule Indexer.BlockFetcher do
           transactions: transactions_with_receipts
         })
 
+      balances_params =
+        Balances.params(%{blocks_params: blocks, logs_params: logs, transactions_params: transactions_with_receipts})
```
Comment (alexgaribay) [inline apps/indexer/lib/indexer/block_fetcher.ex]: I think we'd want to parse token transfers for the `to_address_hash` that comes from one of the log topics and include it in the balance fetcher.

Comment (KronicDeth) [reply apps/indexer/lib/indexer/block_fetcher.ex]: Can we do that now or will it require more work on tokens from you?  Where's the pre-existing code that handles this?

Comment (alexgaribay) [reply apps/indexer/lib/indexer/block_fetcher.ex]: https://github.com/poanetwork/poa-explorer/blob/master/apps/indexer/lib/indexer/block_fetcher.ex#L197 
for where you can use the data in scope.

https://github.com/poanetwork/poa-explorer/blob/master/apps/indexer/lib/indexer/token_transfers.ex#L29-L67
is the shape of the token transfer params that you can extract addresses and block numbers.

Comment (KronicDeth) [reply apps/indexer/lib/indexer/block_fetcher.ex]: Holding for adding the token addresses, but everyone feel free to review the rest.

Comment (acravenho) [reply apps/indexer/lib/indexer/block_fetcher.ex]: @alexgaribay If you're going to add the `to_address_hash`, we should add the `from_address_hash` as well.

Comment (alexgaribay) [reply apps/indexer/lib/indexer/block_fetcher.ex]: @acravenho They are part of token transfers but they just need to be accounted for in the balances portion.

**Comment by igorffs** [comment]
> Note: This does not fix the underlying issue with Ecto.Repo.stream that killing the node leaves the query running in Postgres. This just makes the query that hangs take less time, so it is less likely to be running on node death. Fixing the zombie Postgres query will require changes upstream in Ecto.

Does it make sense to remove the `Resolves #491` so it doesn't close the issue?

File: apps/explorer/lib/explorer/chain.ex [hunk 2]
```diff
@@ -941,27 +751,9 @@ defmodule Explorer.Chain do
       fn ->
         query =
           from(
-            address in Address,
```
Comment (igorffs) [inline apps/explorer/lib/explorer/chain.ex]: Niiice ✨ 👏

File: apps/explorer/priv/repo/migrations/20180717204948_create_balances.exs [hunk 3]
```diff
@@ -5,11 +5,13 @@ defmodule Explorer.Repo.Migrations.CreateBalances do
     create table(:balances, primary_key: false) do
       add(:address_hash, references(:addresses, column: :hash, type: :bytea), null: false)
       add(:block_number, :bigint, null: false)
-      add(:value, :numeric, precision: 100, null: false)
+      # null until fetched
+      add(:value, :numeric, precision: 100, null: true)
```
Comment (igorffs) [inline apps/explorer/priv/repo/migrations/20180717204948_create_balances.exs]: Would it make sense to define a `nil` default for this column?

**Comment by igorffs** [comment]
@KronicDeth do you think it would be nice to use a new column for managing this Balance state?

I get the impression that by defining this new responsibility to the `value` column makes this new aspect very implicit. I think that a new column (`fetched`?) could help us explicit this scenario in our data layer and also provide an ambiguous attribute if we need to deal with this scenario in our presentation layer.

wdyt?

File: apps/explorer/lib/explorer/chain.ex [hunk 4]
```diff
@@ -722,211 +722,21 @@ defmodule Explorer.Chain do
   When there are addresses, the `reducer` is called for each `t:Explorer.Chain.Address.t/0` `hash` and all
   `t:Explorer.Chain.Block.t/0` `block_number` that address is mentioned.
 
-  An `t:Explorer.Chain.Address.t/0` `hash` can be used as an `t:Explorer.Chain.Block.t/0` `miner_hash`.
```
Comment (igorffs) [inline apps/explorer/lib/explorer/chain.ex]: I've noticed that there aren't new tests in the `chain_test`,  these scenarios being deleted here are already covered there?

File: apps/explorer/priv/repo/migrations/20180717204948_create_balances.exs (hunk 3 above)
Comment (KronicDeth) [reply apps/explorer/priv/repo/migrations/20180717204948_create_balances.exs]: Yes

File: apps/explorer/lib/explorer/chain.ex (hunk 4 above)
Comment (KronicDeth) [reply apps/explorer/lib/explorer/chain.ex]: Yes, it turned out the tests in `chain_test.exs` test before and after the balance existed, so the ones in the doc are redundant and don't follow our new recommendations, so I removed these.

**Comment by KronicDeth** [comment]
> I get the impression that by defining this new responsibility to the value column makes this new > aspect very implicit. I think that a new column (fetched?) could help us explicit this scenario in our data layer and also provide an ambiguous attribute if we need to deal with this scenario in our presentation layer.

I'll make a timestamp column since that's what we do we async fetch in other fields.

**Comment by KronicDeth** [comment]
> Does it make sense to remove the Resolves #491 so it doesn't close the issue?

It's iffy, normally in my open source projects, where I can't do a full fix, I would allow this to close #491 and reopen it if it still occurs.  I wouldn't leave it open until a fix in Ecto because I'm not working on a fix in Ecto or planning on one.  If I was, I would make only the Ecto issue be open.

**Comment by KronicDeth** [comment]
@igorffs your fixes are in.

File: apps/explorer/lib/explorer/chain.ex [hunk 5]
```diff
@@ -948,27 +758,9 @@ defmodule Explorer.Chain do
...
-                address.hash in [transaction.from_address_hash, transaction.to_address_hash],
-            left_join: block in Block,
-            on: block.hash == transaction.block_hash or block.miner_hash == address.hash,
-            left_join: balance in Balance,
-            on: balance.address_hash == address.hash and balance.block_number == block.number,
-            where: not is_nil(block.number) and is_nil(balance.address_hash) and is_nil(balance.block_number),
-            group_by: [address.hash, block.number],
-            select: %{address_hash: address.hash, block_number: block.number}
+            balance in Balance,
+            where: is_nil(balance.value),
```
Comment (igorffs) [inline apps/explorer/lib/explorer/chain.ex]: Would it make sense to use the new `value_fetched_at` in our queries since it represent this non-fetched state (as we've discussed in https://github.com/poanetwork/poa-explorer/pull/505#issuecomment-411477956 and https://github.com/poanetwork/poa-explorer/pull/505#issuecomment-411481585)?

Comment (KronicDeth) [reply apps/explorer/lib/explorer/chain.ex]: Sure

File: apps/indexer/lib/indexer/balances.ex [hunk 6]
```diff
@@ -0,0 +1,90 @@
+defmodule Indexer.Balances do
```
Comment (igorffs) [inline apps/indexer/lib/indexer/balances.ex]: Can we have tests for this module?

File: apps/indexer/lib/indexer/block_fetcher.ex [hunk 7]
```diff
@@ -203,11 +209,20 @@ defmodule Indexer.BlockFetcher do
           transactions: transactions_with_receipts
         })
 
+      balances_params =
+        Balances.params(%{
```
Comment (igorffs) [inline apps/indexer/lib/indexer/block_fetcher.ex]: Have you considered generating the Balances from the extracted Addresses above ☝️? 

At this point, we've already reduced all other entities to "denormalized" and unique Addresses and we wouldn't need to deal with the specificity of all of these fetched data. It seem to make sense even due to the relation between the Address -> Balance.

Comment (KronicDeth) [reply apps/indexer/lib/indexer/block_fetcher.ex]: Yes, I considered it, but the balances want all block numbers while the address just want the greatest block number.  If we did it the other way, and tried to derive the addresses from the balances, the contract code wouldn't be available since balances don't care about that.  So the only way to do a single pass is to extract a weird blend of balances and addresses and then loop over that list twice to get just the address fields and just the balance fields.

## Separate addresses and balances (now)

1. Loop over all params_lists get addresses_params
2. Loop over all params_lists get balances_params

## Combined

1. Loop over all params_list get superset params
2. Loop over superset params get addresses_params
3. Loop over superset params get balances_params

The combined cycle also produces the superset params are used for only a small time.

I chose this way instead of the combine cycle because the code is easier to understand I think when address extractor only cares about address fields and balances only cares about balances_fetch params_lists.

File: apps/explorer_web/test/support/feature_case.ex [hunk 8]
```diff
@@ -26,4 +28,12 @@ defmodule ExplorerWeb.FeatureCase do
     session = Wallaby.Browser.resize_window(session, 1200, 800)
     {:ok, session: session}
   end
+
+  def assert_has_eventually(session, query) do
```
Comment (KronicDeth) [inline apps/explorer_web/test/support/feature_case.ex]: @jimmay5469, @Stamates, @katibest, @tmecklem can I get one of y'all's review on if this makes sense?

Comment (KronicDeth) [reply apps/explorer_web/test/support/feature_case.ex]: Never mind, [it still didn't work after 60 second](https://circleci.com/gh/poanetwork/poa-explorer/17218).  Removing tests instead.  Is there a pre-existing issue for the flaky tests or should I open one?

Comment (Stamates) [reply apps/explorer_web/test/support/feature_case.ex]: Yes... (#522)[https://github.com/poanetwork/poa-explorer/issues/522]

File: apps/explorer_web/test/explorer_web/features/viewing_chain_test.exs [hunk 9]
```diff
@@ -146,22 +146,6 @@ defmodule ExplorerWeb.ViewingChainTest do
       |> refute_has(ChainPage.transaction(last_shown_transaction))
     end
 
-    test "count of non-loaded transactions live update when batch overflow", %{session: session, block: block} do
```
Comment (KronicDeth) [inline apps/explorer_web/test/explorer_web/features/viewing_chain_test.exs]: Removed due to flakiness

File: apps/explorer_web/test/explorer_web/features/viewing_transactions_test.exs [hunk 10]
```diff
@@ -97,33 +97,6 @@ defmodule ExplorerWeb.ViewingTransactionsTest do
       |> TransactionListPage.visit_page()
       |> assert_has(TransactionListPage.contract_creation(transaction))
     end
-
-    test "viewing new transactions via live update on list page", %{session: session} do
```
Comment (KronicDeth) [inline apps/explorer_web/test/explorer_web/features/viewing_transactions_test.exs]: Removed due to flakiness

File: apps/explorer_web/test/explorer_web/features/viewing_transactions_test.exs [hunk 11]
```diff
@@ -97,33 +97,6 @@ defmodule ExplorerWeb.ViewingTransactionsTest do
...
-        :transaction
-        |> insert()
-        |> with_block()
-
-      Notifier.handle_event({:chain_event, :transactions, [transaction.hash]})
-
-      assert_has(session, TransactionListPage.transaction(transaction))
-    end
-
-    test "count of non-loaded transactions on list page live update when batch overflow", %{session: session} do
```
Comment (KronicDeth) [inline apps/explorer_web/test/explorer_web/features/viewing_transactions_test.exs]: Removed due to flakiness

File: apps/explorer_web/test/explorer_web/features/viewing_chain_test.exs (hunk 9 above)
Comment (jimmay5469) [reply apps/explorer_web/test/explorer_web/features/viewing_chain_test.exs]: I think this is probably the right thing to do. We're gonna join in on your standup today for a couple other short discussions so we'll discuss this as well.

**Comment by KronicDeth** [comment]
Tests are green again.  I need an Approve from you @igorffs to merge.

File: apps/indexer/lib/indexer/balances_test.exs [hunk 12]
```diff
@@ -0,0 +1,16 @@
+defmodule Indexer.BalancesTest do
+  use ExUnit.Case, async: true
+
+  alias Indexer.Balances
+
+  describe "params_set/1" do
+    test "extracts block miner_hash" do
```
Comment (igorffs) [inline apps/indexer/lib/indexer/balances_test.exs]: This covers only the behavior from block params, let's make sure the other ones (internal_transactions_params, logs_params, token_transfers_params and transactions_params) are tested too because they can change differently. 🙌 

After that :shipit: ❤️

File: apps/indexer/lib/indexer/block_fetcher.ex (hunk 7 above)
Comment (igorffs) [reply apps/indexer/lib/indexer/block_fetcher.ex]: Nice, thanks for the explanation ❤️

**Comment by goodsoft** [comment]
@KronicDeth do I understand correctly that [extracting balances from internal transactions](https://github.com/poanetwork/blockscout/pull/505/files#diff-1e43ae77d4bc12f87c3146547e6bd4d9R53) was implemented but [never actually used](https://github.com/poanetwork/blockscout/pull/505/files#diff-97314e42f31b577101fed6dbeef4fc4dR212) anywhere except tests?

P.S. Sorry for necroposting.
