### PR TITLE
 Fetch realtime internal transactions and balances synchronously

### LINKED ISSUE #366: Real-time indexer should fetch internal transactions and balances together
The real-time indexer should fetch transactions, receipts, internal transactions, and balances together and not defer these processes. It's a bad user experience having to wait for these to populate. 

### Steps to reproduce

1. Send a transaction to address `0x2e185980ba1376b98f27d5712305f5413a4eec43`
2. Enter 0 POA
3. Enter `0x412a5a6d` in the data field.
4. Send the transaction.

### Expected behaviour

You should see a new contract created in the internal transactions section along with the call to the contract immediately. 

### Actual behaviour

It took 12 minutes for this internal transaction values to populate.

### PR DESCRIPTION
**Pull request by KronicDeth**
Fixes #366

### Enhancements
*  Separate `Catchup`, `Realtime`, `Supervisor`, and `BlockFetcher` states
* Move `Receipts` functions out of `BlockFetcher`.  (Functions were previously private, so not a public API change.)
*  Switch `Explorer.Chain.import` options to maps
    1. Allows for easier composing with `put_in` than `Keyword.t`
    2. Allows more precise specs as individual options can be marked as `optional` or `required` while the `Keyword.t` pattern makes it seem like everything is optional.

### Bug Fixes
* `catchup_block_number` can't be set in state because it is set in a separate task, so have the `Task` return it instead of storing it in a state field.
* Queuing the internal transactions and balances to be fetched asynchronously for realtime blocks lead to upto 15 minute delay between when a block appeared and the internal transaction was drained from the queue.  It is a better user experience to not see the realtime blocks at all than to see them incomplete, so fetch the internal transactions and then the balances before importing the whole tree of data instead of using the catchup asynchronous queues.

### Incompatible Changes
* Move `catchup_task` out of `Index.BlockFetcher` into `Index.BlockFetcher.Catchup`, so it is easier to spot catchup vs realtime vs common code.
* Move supervision aspect to `BlockFetcher.Supervisor` and leave only the actual fetching code in `BlockFetcher`.
* `BlockFetcher.Catchup` and `BlockFetcher.Realtime` get their own structs, which use `BlockFetcher` struct.  This better emphasizes that `Catchup` and `Realtime` are both block fetchers.  The `BlockFetcher.Catchup` and `BlockFetcher.Realtime` structs move into Supervisor's struct fields.
*  `Explorer.Chain.import` options are now maps instead of `Keyword.t`
    
## Upgrading

* Callers of `Exploer.Chain.import` need to switch the `options` from `Keyword.t` to `map` at the root and first level down.

### CODE REVIEW

File: apps/indexer/lib/indexer/block_fetcher.ex [hunk 1]
```diff
@@ -3,40 +3,68 @@ defmodule Indexer.BlockFetcher do
   Fetches and indexes block ranges from gensis to realtime.
```
Comment (alexgaribay) [inline apps/indexer/lib/indexer/block_fetcher.ex]: Should the doc be updated to reflect that it just fetches data and has no concern of real-time or catchup?

Comment (KronicDeth) [reply apps/indexer/lib/indexer/block_fetcher.ex]: Yeah

**Comment by acravenho** [comment]
@KronicDeth I'm currently seeing the following error while indexing `core`. I can switch to `sokol` if you think this is a node issue. 

Every 5 blocks the blockFetcher exits skipping 2-3 blocks.

```
[error] Realtime index stream exited with reason ({{:badkey, "0x11c4469d974f8af5ba9ec99f3c42c07c848c861c"}, [{:maps, :get, ["0x11c4469d974f8af5ba9ec99f3c42c07c848c861c", %{"0x40b18103537c0f15d5e137dd8ddd019b84949d16" => 3946079, "0x5ee341ac44d344ade1ca3a771c59b98eb2a77df2" => 3946079, "0x698bf6943bab687b2756394624aa183f434f65da" => 3946079}], []}, {Indexer.BlockFetcher.Realtime, :"-balances/2-fun-0-", 2, [file: 'lib/indexer/block_fetcher/realtime.ex', line: 121]}, {Enum, :"-map/2-lists^map/1-0-", 2, [file: 'lib/enum.ex', line: 1294]}, {Indexer.BlockFetcher.Realtime, :balances, 2, [file: 'lib/indexer/block_fetcher/realtime.ex', line: 120]}, {Indexer.BlockFetcher.Realtime, :import, 2, [file: 'lib/indexer/block_fetcher/realtime.ex', line: 72]}, {Indexer.BlockFetcher, :insert, 2, [file: 'lib/indexer/block_fetcher.ex', line: 134]}, {Task.Supervised, :do_apply, 2, [file: 'lib/task/supervised.ex', line: 88]}, {Task.Supervised, :reply, 5, [file: 'lib/task/supervised.ex', line: 38]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}).  The next realtime index task will fill the missing block if the lastest block number has not advanced by then or the catch up index will fill the missing block.
[error] Task #PID<0.16755.0> started from #PID<0.16754.0> terminating
** (KeyError) key "0x11c4469d974f8af5ba9ec99f3c42c07c848c861c" not found in: %{"0x40b18103537c0f15d5e137dd8ddd019b84949d16" => 3946079, "0x5ee341ac44d344ade1ca3a771c59b98eb2a77df2" => 3946079, "0x698bf6943bab687b2756394624aa183f434f65da" => 3946079}
    (stdlib) :maps.get("0x11c4469d974f8af5ba9ec99f3c42c07c848c861c", %{"0x40b18103537c0f15d5e137dd8ddd019b84949d16" => 3946079, "0x5ee341ac44d344ade1ca3a771c59b98eb2a77df2" => 3946079, "0x698bf6943bab687b2756394624aa183f434f65da" => 3946079})
    (indexer) lib/indexer/block_fetcher/realtime.ex:121: anonymous fn/2 in Indexer.BlockFetcher.Realtime.balances/2
    (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
    (indexer) lib/indexer/block_fetcher/realtime.ex:120: Indexer.BlockFetcher.Realtime.balances/2
    (indexer) lib/indexer/block_fetcher/realtime.ex:72: Indexer.BlockFetcher.Realtime.import/2
    (indexer) lib/indexer/block_fetcher.ex:134: Indexer.BlockFetcher.insert/2
    (elixir) lib/task/supervised.ex:88: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:38: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: &:erlang.apply/2
    Args: [#Function<7.112724865/1 in Indexer.BlockFetcher.stream_import/1>, [3946079..3946080]]
[error] GenServer #PID<0.16753.0> terminating
** (KeyError) key "0x11c4469d974f8af5ba9ec99f3c42c07c848c861c" not found in: %{"0x40b18103537c0f15d5e137dd8ddd019b84949d16" => 3946079, "0x5ee341ac44d344ade1ca3a771c59b98eb2a77df2" => 3946079, "0x698bf6943bab687b2756394624aa183f434f65da" => 3946079}
    (stdlib) :maps.get("0x11c4469d974f8af5ba9ec99f3c42c07c848c861c", %{"0x40b18103537c0f15d5e137dd8ddd019b84949d16" => 3946079, "0x5ee341ac44d344ade1ca3a771c59b98eb2a77df2" => 3946079, "0x698bf6943bab687b2756394624aa183f434f65da" => 3946079})
    (indexer) lib/indexer/block_fetcher/realtime.ex:121: anonymous fn/2 in Indexer.BlockFetcher.Realtime.balances/2
    (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
    (indexer) lib/indexer/block_fetcher/realtime.ex:120: Indexer.BlockFetcher.Realtime.balances/2
    (indexer) lib/indexer/block_fetcher/realtime.ex:72: Indexer.BlockFetcher.Realtime.import/2
    (indexer) lib/indexer/block_fetcher.ex:134: Indexer.BlockFetcher.insert/2
    (elixir) lib/task/supervised.ex:88: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:38: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:EXIT, #PID<0.16748.0>, {{:badkey, "0x11c4469d974f8af5ba9ec99f3c42c07c848c861c"}, [{:maps, :get, ["0x11c4469d974f8af5ba9ec99f3c42c07c848c861c", %{"0x40b18103537c0f15d5e137dd8ddd019b84949d16" => 3946079, "0x5ee341ac44d344ade1ca3a771c59b98eb2a77df2" => 3946079, "0x698bf6943bab687b2756394624aa183f434f65da" => 3946079}], []}, {Indexer.BlockFetcher.Realtime, :"-balances/2-fun-0-", 2, [file: 'lib/indexer/block_fetcher/realtime.ex', line: 121]}, {Enum, :"-map/2-lists^map/1-0-", 2, [file: 'lib/enum.ex', line: 1294]}, {Indexer.BlockFetcher.Realtime, :balances, 2, [file: 'lib/indexer/block_fetcher/realtime.ex', line: 120]}, {Indexer.BlockFetcher.Realtime, :import, 2, [file: 'lib/indexer/block_fetcher/realtime.ex', line: 72]}, {Indexer.BlockFetcher, :insert, 2, [file: 'lib/indexer/block_fetcher.ex', line: 134]}, {Task.Supervised, :do_apply, 2, [file: 'lib/task/supervised.ex', line: 88]}, {Task.Supervised, :reply, 5, [file: 'lib/task/supervised.ex', line: 38]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}}
State: %Indexer.Sequence{current: nil, queue: {[], []}, step: 2}
```

**Comment by KronicDeth** [comment]
Thanks @acravenho, there's problem some bug in the address merging code.  It's a different path than the async merging and was difficult to trigger because I kept getting empty blocks yesterday.  Hopefully, with the new load of users I can trigger locally.

**Comment by KronicDeth** [comment]
Thankfully, your bug report has block numbers, `3946079..3946080`, so I can force a test to use that range, but with the realtime indexer to hopefully trigger the bug in test.

**Comment by acravenho** [comment]
Here are a few other ranges:
- 3946154 - 3946155
- 3946153 - 3946154
- 3946153 - 3946154 (again)
- 3946148 - 3946149

**Comment by KronicDeth** [comment]
@acravenho the lastest version with https://github.com/poanetwork/poa-explorer/pull/489/commits/79d37cd1a43382621e244bccb5fb18daf41afbe3 is working for me against `core`.  Please retest to confirm.

File: apps/indexer/lib/indexer/block_fetcher/catchup.ex [hunk 2]
```diff
@@ -0,0 +1,174 @@
...
+  alias Explorer.Chain
+  alias Indexer.{BalanceFetcher, BlockFetcher, BoundInterval, InternalTransactionFetcher, Sequence}
+
+  @behaviour BlockFetcher
+
+  @enforce_keys ~w(block_fetcher bound_interval)a
+  defstruct ~w(block_fetcher bound_interval task)a
+
+  def new(named_arguments) when is_list(named_arguments) do
+    common_block_fetcher = Keyword.fetch!(named_arguments, :block_fetcher)
```
Comment (alexgaribay) [inline apps/indexer/lib/indexer/block_fetcher/catchup.ex]: Would it make sense to match on `%BlockFetcher{}` here so that it's apparent that the `:block_fetcher` arg should be of that struct?

File: apps/indexer/lib/indexer/block_fetcher/catchup.ex [hunk 3]
```diff
@@ -0,0 +1,174 @@
...
+  end
+
+  @async_import_remaning_block_data_options ~w(address_hash_to_fetched_balance_block_number transaction_hash_to_block_number)a
+
+  @impl BlockFetcher
+  def import(_, options) when is_map(options) do
+    {async_import_remaning_block_data_options, chain_import_options} =
+      Map.split(options, @async_import_remaning_block_data_options)
+
+    with {:ok, results} = ok <- Chain.import(chain_import_options) do
```
Comment (alexgaribay) [inline apps/indexer/lib/indexer/block_fetcher/catchup.ex]: Renaming `ok` to something like `import_result` would be more descriptive of the variable at a glance.

File: apps/indexer/lib/indexer/block_fetcher/realtime.ex [hunk 4]
```diff
@@ -0,0 +1,192 @@
...
+
+  @behaviour BlockFetcher
+
+  @enforce_keys ~w(block_fetcher interval)a
+  defstruct block_fetcher: nil,
+            interval: nil,
+            task_by_ref: %{}
+
+  def new(named_arguments) when is_list(named_arguments) do
+    common_block_fetcher = Keyword.fetch!(named_arguments, :block_fetcher)
```
Comment (alexgaribay) [inline apps/indexer/lib/indexer/block_fetcher/realtime.ex]: See comment other comment about matching on the struct.

File: apps/indexer/lib/indexer/block_fetcher/catchup.ex (hunk 2 above)
Comment (KronicDeth) [reply apps/indexer/lib/indexer/block_fetcher/catchup.ex]: I'll just switch to map arguments as it will allow me to match on the required arguments without the awkward double `=` in `%BlockFetcher{} = common_block_fetcher = Keyword.fetch!(named_arguments, :block_fetcher)`)

File: apps/indexer/lib/indexer/block_fetcher/catchup.ex (hunk 3 above)
Comment (KronicDeth) [reply apps/indexer/lib/indexer/block_fetcher/catchup.ex]: It's called `ok` because it's is the entire `ok` tuple.  `import_result` to me would be only the `results` variable.

```
ok = {:ok, result}
error = {:error, reason}
```
